-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 20:02:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CommWindow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommWindow` (
  `CommWindow_id` INT NOT NULL,
  `Calendar_id` INT NULL,
  `Name` VARCHAR(45) NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `Duration` DATETIME NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  `Enabled` TINYINT(1) NULL,
  PRIMARY KEY (`CommWindow_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandResponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandResponse` (
  `CommandResponse_id` VARCHAR(45) NOT NULL,
  `Command_id` VARCHAR(45) NULL,
  `ResponseStatus` VARCHAR(45) NULL,
  `ResponseData` VARCHAR(45) NULL,
  `DateTimeReceived` DATETIME NULL,
  PRIMARY KEY (`CommandResponse_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Command` (
  `Command_id` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` TEXT(150) NULL,
  `ValidUntil` DATETIME NULL,
  `Enabled` TINYINT(1) NULL,
  PRIMARY KEY (`Command_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandWindowCommand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandWindowCommand` (
  `CommWindowCommand_id` VARCHAR(10) NOT NULL,
  `Command_id` VARCHAR(10) NULL,
  `CommandWeight_id` VARCHAR(10) NULL,
  `Date` DATETIME NULL,
  `Description` TEXT(150) NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  `Enabled` TINYINT(1) NULL,
  PRIMARY KEY (`CommWindowCommand_id`),
  CONSTRAINT `CommandWindowId_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`CommWindow` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Priority` (
  `Priority_id` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Priority_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandPriority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandPriority` (
  `CommandPriority_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CommandPriority_id`),
  CONSTRAINT `PriorityId_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Priority` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandDuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandDuration` (
  `CommandDuration_id` VARCHAR(10) NOT NULL,
  `Duration` DOUBLE NULL,
  PRIMARY KEY (`CommandDuration_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandWeight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandWeight` (
  `CommandWieght_id` VARCHAR(10) NOT NULL,
  `Weight` INT NULL,
  PRIMARY KEY (`CommandWieght_id`),
  CONSTRAINT `CommandPriorityId_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`CommandPriority` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CommandDurationId_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`CommandDuration` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
